spring.application.name=backend-application

# 1. Đường dẫn kết nối đến MySQL Cloud (Lấy từ dòng URL trong ảnh của bạn)
spring.datasource.url=jdbc:mysql://mysql-btl-nhom-quanlithietbi.j.aivencloud.com:18171/defaultdb?useSSL=true&trustServerCertificate=true

# 2. Tài khoản và mật khẩu đăng nhập (Lấy chính xác từ mục Authentication trên ảnh)
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_bNkiIetkK-A6x5Y5LVT

# 3. Khai báo Driver sử dụng để kết nối dữ liệu
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# Không cho Java tự sinh bảng hoặc thay đổi cấu trúc bảng dưới database (Chỉ đọc cấu trúc sẵn có)
spring.jpa.hibernate.ddl-auto=none

# Hiển thị các câu lệnh SQL dưới Terminal để bạn dễ theo dõi khi debug
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ép HikariPool phải kiểm tra kết nối trước khi đưa cho Hibernate dùng
spring.datasource.hikari.connection-test-query=SELECT 1
# Thời gian tối đa giữ kết nối sống (ngắn hơn thời gian timeout của Cloud)
spring.datasource.hikari.max-lifetime=600000
# Thời gian chờ kết nối tối đa
spring.datasource.hikari.connection-timeout=20000